### ISSUE TITLE
Multi users

### ISSUE THREAD

**Issue by AC-Lover** [XTLS/Xray-examples#104]
I want to use @trojan-ws for multiple users but only one user can use what is the solution?
@UZziell

I want to use trojan + ws + tls + cdn (cloudflare) with one port (443) and several users!

x-ui : https://github.com/FranzKafkaYu/x-ui/

![image](https://user-images.githubusercontent.com/49290111/210705435-ff015a6a-fbf0-46d4-9bef-72eb36e42bab.png)

![image](https://user-images.githubusercontent.com/49290111/210705467-b9f0e4e3-557f-4222-8e94-b890869c1770.png)

![image](https://user-images.githubusercontent.com/49290111/210705502-d80f1f90-d587-42a9-a70b-b831fe6d90e6.png)

**Comment by MHSanaei** [comment]
remove your listening ip

**Comment by AC-Lover** [comment]
> 

For both?
and `acceptProxyProtocol `is enabled?

**Comment by AC-Lover** [comment]
> remove your listening ip

For both?
and `acceptProxyProtocol` is enabled?
