### ISSUE TITLE
docker 安装 all in one只有trojan能通为什么啊？

### ISSUE THREAD

**Issue by Pacio** [XTLS/Xray-examples#105]
报错如下：
![image](https://user-images.githubusercontent.com/6836705/210928934-5445e496-3ef5-45fa-a694-b3f3c70e5891.png)

**Comment by UZziell** [comment]
I can't tell what the problem is. Which combination doesn't work? Is the client's configuration OK? I will add client json configurations soon. See if that solves it.

next time redact IPs as well. dumb dictators are around

**Comment by Fangliding** [comment]
似乎回落没有正确配置
