### ISSUE TITLE
all-in-one nginx error but xray is running

### ISSUE THREAD

**Issue by wssvpn** [XTLS/Xray-examples#108]
can you help me, all-in-one nginx error but xray is running

![Screenshot_2023-01-12-05-29-47-63_61c78dc80ee02b53007c815fefe993e3](https://user-images.githubusercontent.com/121462190/211933199-b80c8f62-4f66-42e1-81d7-d86bb8fb43c7.jpg)

**Comment by old-joker** [comment]
Apparently Nginx does not clean up the sockets itself.
Try this:
`rm /dev/shm/{h1.sock,h2c.sock} && nginx -t && systemctl restart nginx `
