### ISSUE TITLE
Reverse proxy from nginx to caddy to vless

### ISSUE THREAD

**Issue by vahidx4r4x** [XTLS/Xray-examples#111]
Hi.
Thanks for your hard work.
I have 2 servers 
On server A, I have nginx for reverse proxying all traffic to server B.
On server B, I have caddy for reverse proxying traffic to localhost vless.
I can connect to my server B and vless without problem.
But what I want is connecting to server A with /path1 and forwarding all the traffic to server B with /path2 

How should I config my server A's nginx config?

Tnx

**Comment by Fangliding** [comment]
与example无关
