### ISSUE TITLE
config.json 中的 “outbounds” 里面需要加上“settings"，xray才能正常启动

### ISSUE THREAD

**Issue by picklefan** [XTLS/Xray-examples#115]
Xray-example 里面的配置文件中的 outbounds 通常为
```
"outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
```
而只有当“outbounds”项里有“settings”时，xray才能启动：
```
"outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct",
            "settings":{}
        },
        {
            "protocol": "blackhole",
            "tag": "block",
            "settings":{}
        }
    ]
```
希望能在examples 中加上“settings”
我的xray版本为1.7.2，操作系统为Debian 11 x64， Ubuntu-22.04 x64

**Comment by chika0801** [comment]
在vps端没加"settings":{}也是正常启动的

**Comment by hacker5510** [comment]
贴完整配置吧。

**Comment by picklefan** [comment]
这真是玄学问题啊，我把settings删了，也可以运行了，但是就在3个小时前，我把settings删了就不能启动了，我还试了两次才发的issue。不过之前系统是ubuntu，崩了之后刚换的Debian10没有问题，还有一台Debian11也没有问题。

以前v2ray也出现过少了settings不能启动这种情况，所以我才想到把settings加上去测试的。没想到竟是这种玄学问题。

但是这个问题是真的存在的，好几年前v2ray就有这种情况，所以我写配置都加了settings，今天是抄配置不过，加了settings才过，所以发了issue。

希望没有其他人出现这种奇怪的问题。
