### ISSUE TITLE
[all-in-one] H2 unexpected status 400

### ISSUE THREAD

**Issue by dugong-lewat** [XTLS/Xray-examples#116]
![Screenshot_2023-01-31-11-13-45-03_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/110967975/215661670-d3e20d0c-7ce9-4720-b7b8-4ac99d63e0fc.jpg)

Anyone can help me, only H2 error status 400

**Comment by Fangliding** [comment]
no more info
