### ISSUE TITLE
QUIC multiple connection issue?

### ISSUE THREAD

**Issue by yaser-k** [XTLS/Xray-examples#118]
I able to just establish 1 quic connection for each node. the second connection can't connect or if I use 2 quic in routing section, both connection stop working,
is it something related to quic design or implementation?

**Comment by SakuraSakuraSakuraChan** [comment]
Xray's QUIC is not recommended, try this
https://github.com/e1732a364fed/v2ray_simple/blob/main/examples/quic.server.toml
