### ISSUE TITLE
timeout 52w

### ISSUE THREAD

**Issue by iainlau** [XTLS/Xray-examples#123]
看 nginx 配置文件，timeout 都是 52w
超时设这么大，有什么讲究吗？
有没有什么影响？不懂😂
 @xqzr

**Comment by chika0801** [comment]
> 看 nginx 配置文件，timeout 都是 52w 超时设这么大，有什么讲究吗？ 有没有什么影响？不懂😂 @xqzr

没讲究，你写好久随意233

**Comment by xqzr** [comment]
因为没有∞
Nginx 不干涉超时，由 Xray 管理
