### ISSUE TITLE
用caddy反代vless+grpc+tls始终不成功

### ISSUE THREAD

**Issue by wangdaye078** [XTLS/Xray-examples#137]
Caddyfile如下
www.tt.xyz {
	@grpc {
		protocol grpc
		path  /grpctest/*
	}
	reverse_proxy @grpc localhost:444 {
		transport http {
			versions h2c
		}
	}
	root * /var/www/html
	file_server
}
server.json如下
....
  "inbounds": [
    {
      "port": 444,
      "protocol": "vless",
.....
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "grpctest",
.....
用v2rayN配置客户端端口设置为444的时候可以代理正常使用
浏览器直接访问www.tt.xyz可以正确访问
但是用v2rayN端口设置443的时候，显示“ 当前服务的真连接延迟: -1 ms”，代理无法正常使用
caddy加上日志后输出
****,"logger":"http.log.error","msg":"write tcp [::1]:52444->[::1]:444: write: broken pipe","request":{"remote_ip":"78.78.78.78","remote_port":"9540","proto":"HTTP/2.0","method":"POST","host":"www.tt.xyz","uri":"/grpctest/Tun",****,"duration":0.001229619,"status":502,"err_id":"qudiuqjxc","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}

以上的域名和IP做了修改。

用netstat -nap可以找到
tcp6       0      0 :::444                  :::*                    LISTEN      26965/xray  
如果caddy配置改为reverse_proxy @grpc 127.0.0.1:444
日志错误变成****"msg":"unexpected EOF"****，忽略部分和上面一致

软件版本都是最新。有人知道是怎么回事吗？

**Comment by wangdaye078** [comment]
尝试了各种组合
grpc换ws换h2，caddy换成nginx，都没成功，只有xray回落到nginx成功了。

**Comment by qist** [comment]
server.json 配置了证书。配置了就是 grpcs 127.0.0.1:444

**Comment by wangdaye078** [comment]
server.json无论是否配置证书，Caddyfile写成localhost:444，127.0.0.1:444，或者只写:444，都无法正常使用，
错误有
"write tcp 127.0.0.1:36212->127.0.0.1:444: write: broken pipe"
或者
write tcp [::1]:45678->[::1]:444: write: broken pipe
其他都一样。
如果
https://github.com/grpc {
protocol grpc
path /grpctest/*
}
改成
https://github.com/grpc {
protocol grpc
path /grpctest/Tun

}
错误有时候会变成
"msg":"unexpected EOF"，其他部分还是一样

**Comment by wangdaye078** [comment]
另外还试了反代vless+h2+tls，caddy2里面配置
	reverse_proxy /grpctest 127.0.0.1:444 {
		transport http {
			versions h2c
		}
	}
还有反代vless+ws+tls，caddy2里面配置
	@websockets {
		path /grpctest
		header Connection Upgrade
		header Upgrade websocket
	}
	reverse_proxy @websockets 127.0.0.1:444
都不行，后一个的输出是
{"level":"debug","ts":"2023/03/17 23:09:41","logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"127.0.0.1:444","duration":0.000799588,"request":{"remote_ip":"78.78.78.78","remote_port":"12597","proto":"HTTP/1.1","method":"GET","host":"www.ttt.xyz","uri":"/grpctest","headers":{"Upgrade":["websocket"],"X-Forwarded-For":["117.62.128.164"],"X-Forwarded-Proto":["https"],"X-Forwarded-Host":["www.ttt.xyz"],"User-Agent":["Go-http-client/1.1"],"Connection":["Upgrade"],"Sec-Websocket-Key":["qisvQjySzS5qXgXDrEUXqQ=="],"Sec-Websocket-Version":["13"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"www.ttt.xyz"}},"headers":{},"status":400}

**Comment by wangdaye078** [comment]
我好像明白了，server.json里面不能有TLS设置，就是client是vless+ws+tls，server是vless+ws，把tls部分全部交于caddy处理，解密后才反代到server。看了examples确实是这样的，是我看的时候不小心，没事了。不过希望examples的readme里最好能加上这个明确的说明，防止其他和我一样的人，折腾了好几天了。

**Comment by Mengter8** [comment]
thinks!!!
