### ISSUE TITLE
这个VLESS-TCP-XTLS-WHATEVER示例配置没问题吗？

### ISSUE THREAD

**Issue by ilaziness** [XTLS/Xray-examples#142]
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_client/vless_tcp_xtls.json
按照这个配置修改好，用docker的方式运行，提示

```shell
Failed to start: main: failed to load config files: [/etc/xray/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.
```
运行不起来呀。

`"security": "xtls",`要修改成`"security": "tls",`？

**Comment by chika0801** [comment]
这个过时了，查看

https://github.com/chika0801/Xray-examples

**Comment by ilaziness** [comment]
@chika0801 试了，这个仓库的配置可以。
