### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-examples#146]

**Comment by architecturers** [comment]
以前的版本 这俩 搭配 直接不能启动
1.81可以启动了 但是不通
看群里面 有人说 可以搭配使用 
所以来问问

**Comment by chika0801** [comment]
vision不支持tcp的mux，你写非-1记得启动要报错的

**Comment by architecturers** [comment]
那也就是说 支持udp的mux？

**Comment by chika0801** [comment]
看你标题我以为你是问 "concurrency": 能不能非-1用，你协议换其它的组合是可以开的，我是一直没用就是了。

**Comment by architecturers** [comment]
没事 我一会试一试 这是一个新思路

**Comment by architecturers** [comment]
顺便问一下 xray 支持多少种 l4proto 只支持tcp udp吗？
还是tproxy支持的 都支持

**Comment by RPRX** [comment]
https://t.me/projectXtls/68
