### ISSUE TITLE
范例里能不能出个caddy的配置文件

### ISSUE THREAD

**Issue by Ventulus-lab** [XTLS/Xray-examples#147]
常用的那几种配置，都是带Nginx的conf范例的，小白看得一脸懵逼啊，现在caddy用得越来越多，能不能同时写个caddy文件的范例？

**Comment by lxhao61** [comment]
https://github.com/lxhao61/integrated-examples

**Comment by Fangliding** [comment]
想用可以自己写 欢迎PR
