### ISSUE TITLE
Bad key length

### ISSUE THREAD

**Issue by Jaffarrr** [XTLS/Xray-examples#151]
Shadowsocks 2022 issue.
Encryption: 2022-blake3-aes-128-gcm
Password: 3dff0400f23884928851a3698333c21b (example generated by 'openssl rand -hex 16')
Test url error: [[Shadowsocks] ss 2022] test error: create service: parse outbound[0]: bad key length, required 16, got 24
Why bad key length? Version 2.28 is working properly

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022#password

密钥生成命令，参考上方的链接

**Comment by Jaffarrr** [comment]
Thanx
