### ISSUE TITLE
All-in-One-fallbacks-Nginx available for Caddy?

### ISSUE THREAD

**Issue by houmie** [XTLS/Xray-examples#152]
I have to say this set of examples are the best I have seen on the internet. Thank you so much for providing this.
https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx

It explains very clearly how the fallback works from Xray to nginx.

I was wondering if there is any interest to provide a Caddy file instead of nginx?
It seems Caddy is very popular when combined with Xray.

**Comment by houmie** [comment]
@bghandchi Just tagging you, as it was your example. Thank you.

**Comment by bghandchi** [comment]
Not originally my contribution. I made the generate.sh to automatically generate the configs based on this folder. Now I have much better understanding of xray configs. I'll look into it and if possible create a caddy version.

**Comment by houmie** [comment]
Thank you so much, I'm happy to contribute by testing each of them for you.
