### ISSUE TITLE
Certificate expired, forgot to regenerate it.

### ISSUE THREAD

**Issue by PalmTamino** [XTLS/Xray-examples#154]
Im using XTLS VLESS TCP Vision, and my certificate expired today, how do I generate a new one again? I forget because it’s been 90 days and dunno how I did it🥹

**Comment by chika0801** [comment]
You originally how to register to apply for a free SSL certificate, you refer to the method you use on the line. For example, if you applied for a certificate from ACME for 90 days, and ACME renewed it automatically, you may have to restart the xray program manually to get the new certificate to take effect. Check those aspects of the factors too.

**Comment by PalmTamino** [comment]
Thanks, found it!
