### ISSUE TITLE
trajan+ws+tls  fallback，浏览器访问返回404

### ISSUE THREAD

**Issue by crazysvn** [XTLS/Xray-examples#156]
trojan+tcp的fallback是成功的。但trajan+ws+tls  fallback，浏览器访问返回404

XrayR中trajan+ws+tls fallback部分的配置：
EnableFallback: true # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 983 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable

nginx配置：
server {
    listen 983 http2;
    root /www/wwwroot/fake-site; # 改成你自己的路径
    index index.html;
    server_name noname.com; # 改成你自己的域名
}

**Comment by KoinuDayo** [comment]
看看log，既然有返回404那么大概率是fallback成功了，应该只是你的 `index.html` 不存在所以返回404，可以考虑使用nginx自带的index
