### ISSUE TITLE
谁给个 TCP/Socks + QUIC 的配置文件？

### ISSUE THREAD

**Issue by hel1o-wor1d** [XTLS/Xray-examples#157]
因为听说使用QUIC后不用加密，就想用SOCKS+QUIC，但是试了2天没成功。
但是用Vless+quic一下就成功。

**Comment by Fangliding** [comment]
@benjaminyin01 别试了 难用得很

**Comment by benjaminyin01** [comment]
> 

怎么地？按理说不加密效率更高。

**Comment by Fangliding** [comment]
@benjaminyin01 1 效率影响没你想的高 vless和trojan一样不加密 差不了多少 2 带密码的socks5需要整整两个rtt进行握手(作为对比 vless和trojan是0)
