### ISSUE TITLE
谁能提供一下vless+vision+reality的配置文件？

### ISSUE THREAD

**Issue by tjyuli** [XTLS/Xray-examples#158]
想试用一下最新的vless+vision+reality，奈何不会搞配置，谁帮我写个现成的，我学习一下。

**Comment by KoinuDayo** [comment]
https://github.com/chika0801/Xray-examples

**Comment by us254** [comment]
![image](https://github.com/XTLS/Xray-examples/assets/88821507/70764d56-ae75-47e2-84e2-8af4595a7f1d)

**Comment by KoinuDayo** [comment]
https://github.com/XTLS/Xray-examples/pull/159/files#diff-449231779437befa127888514fc2d5a9ee97f30482320a0e236c7fe4f83182cc

**Comment by tjyuli** [comment]
感谢以上各位老师
