### ISSUE TITLE
Reverse SSH Port Forwarding SOCKS as Outbound

### ISSUE THREAD

**Issue by wulfric93** [XTLS/Xray-examples#164]
Hello There 
I live in Iran and we here face so many limitation on internet provided for end users 
but servers in iran face less limitation so :
i have a Iran server which its possible to ssh to it from other free countries like Germany , etc. ...
curranty i use reserve ssh port forwarding and initiate connection from foreign vps in germany , i use x-ui and i currently i have my users on Germany server but i want to move ther user management from germany vps to Iran vps and set socks for outbound , but i've faced a problem here which is there is no UDP support for calling for example 
is there any way to fix this problem  ?

**Comment by Fangliding** [comment]
？
