### ISSUE TITLE
Config request

### ISSUE THREAD

**Issue by sevvian** [XTLS/Xray-examples#165]
Could someone please add config for Xray + trojan + tcp + http masquerade or obfuscation with custom domain or all the proxy protocol that supports http masquerade or obfuscation.

Basically I am trying to use custom http header with custom fake domain . I tried generating config , so far only vmess +tcp + http worked . But I could not generate other config using trojan or vless +xtls+vision + reality with http customer domain header obfuscation. Please help .

**Comment by Fangliding** [comment]
I‘m afraid that's impossible to make reality work with that
