### ISSUE TITLE
VLESS TCP XTLS VISITION明显速度比VLESS TCP TLS慢啊，这正常么？

### ISSUE THREAD

**Issue by korben1029** [XTLS/Xray-examples#169]
用的https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision这个配置

**Comment by chika0801** [comment]
不正常。速度应该是一样的。

**Comment by korben1029** [comment]
> 不正常。速度应该是一样的。

并且移动网络链接不上，不是我一个人，还有人移动网连不上

**Comment by korben1029** [comment]
客户端的SNI是配置我自己的域名，还是混淆用的域名？

**Comment by chika0801** [comment]
> 并且移动网络链接不上，不是我一个人，还有人移动网连不上

这现象其它人也来问过，建议是换VPS商家。

**Comment by korben1029** [comment]
今天看日志，发现了一些警告，不知道是不是这个原因导致的速度慢
2023/12/22 09:38:09 127.0.0.1:56877 accepted //rr2---sn-i3b7knzs.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:09 127.0.0.1:56879 accepted //beacons5.gvt3.com:443 [http >> proxy]
2023/12/22 09:38:10 127.0.0.1:56916 accepted //github.com:443 [http >> proxy]
2023/12/22 09:38:12 127.0.0.1:56992 accepted //github.githubassets.com:443 [http >> proxy]
2023/12/22 09:38:12 127.0.0.1:56993 accepted //avatars.githubusercontent.com:443 [http >> proxy]
2023/12/22 09:38:13 127.0.0.1:57033 accepted //91.108.56.155:443 [http >> proxy]
2023/12/22 09:38:13 127.0.0.1:57034 accepted http://91.108.56.155:80/api [http >> proxy]
2023/12/22 09:38:13 [Warning] [1713153177] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:57034: wsasend: An established connection was aborted by the software in your host machine.
2023/12/22 09:38:15 127.0.0.1:57074 accepted //149.154.167.50:443 [http >> proxy]
2023/12/22 09:38:15 127.0.0.1:57111 accepted //149.154.167.41:443 [http >> proxy]
2023/12/22 09:38:15 127.0.0.1:57112 accepted http://149.154.167.50:80/api [http >> proxy]
2023/12/22 09:38:15 127.0.0.1:57113 accepted http://149.154.167.41:80/api [http >> proxy]
2023/12/22 09:38:15 [Warning] [1588882718] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:57112: wsasend: An established connection was aborted by the software in your host machine.
2023/12/22 09:38:15 [Warning] [496202732] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:57113: wsasend: An established connection was aborted by the software in your host machine.
2023/12/22 09:38:16 127.0.0.1:57147 accepted //rr1---sn-i3b7knlk.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:16 127.0.0.1:57157 accepted //rr1---sn-i3b7knlk.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:16 127.0.0.1:57159 accepted //rr4---sn-i3b7kn6s.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:16 127.0.0.1:57160 accepted //rr4---sn-i3b7kn6s.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:16 127.0.0.1:57163 accepted //rr2---sn-5hnekn7z.googlevideo.com:443 [http >> proxy]
2023/12/22 09:38:16 127.0.0.1:57164 accepted //rr2---sn-5hnekn7z.googlevideo.com:443 [http >> proxy]

**Comment by chika0801** [comment]
这些日志信息，对别人帮你分析没有作用。还是建议你买些有回程优化的VPS商家的机，多试几台VPS。

**Comment by korben1029** [comment]
终于解决我的问题了，我的系统是CentOS7.6，内核是3.10， 当时安装xray的时候就提示我系统版本太老，就没当回事，刚才更新了内核到5.4，开了bbr，然后速度直接起飞，油土鳖速度能上8万
![buyaotaishuang](https://github.com/XTLS/Xray-examples/assets/34670850/fa6da24c-d00e-41fd-b912-2742787f08f2)

**Comment by chika0801** [comment]
啊，其实这些因素，只有靠你自己查。你不说，别人谁也猜不到呀。

**Comment by korben1029** [comment]
> 啊，其实这些因素，只有靠你自己查。你不说，别人谁也猜不到呀。

哈哈，碰运气呗，万一刚好有和我一样问题的

**Comment by chika0801** [comment]
一般来说，提问之前，自己都会在不同VPS上，进行复测，看故障现象能复现得了不。你先把这ISS关闭了吧。

**Comment by korben1029** [comment]
> 一般来说，提问之前，自己都会在不同VPS上，进行复测，看故障现象能复现得了不。你先把这ISS关闭了吧。

我在两台不同的vps上测过了，都有同样的问题，因为我习惯用centos7 哈哈，所以都有通病 哈哈
