### ISSUE TITLE
请教关于route模块的工作逻辑

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-examples#17]
假设outbaounds第一条是proxy出口，那么默认路径就是这个了；如果route中只有关于域名的规则，由于所有的通讯最终都是要通过TCP/IP层发送数据的，由于没有找到关于IP的规则，那么是不是所有流量都会走到Proxy路径上去呢？比如说配置了geosite:geolocation-!cn走proxy这一条rule；那么当客户端访问baidu.com的时候，虽然可能先通过proxy去做了DNS解析，但是拿到解析返回的IP后真正建立TCP的链接的时候由于没有基于该IP的rule，是否会自动走到proxy上去？
Xray是工作在TCP/IP协议的哪一层呢，如果是代理模式貌似还可以理解为工作在应用层，但是透明代理模式由于是通过修改iptables实现的端口转发，那么好像应该在更低层吧，如果在底层如果不控制IP的route是不是就无法有效分流了

**Comment by Bearljj** [comment]
虽然这两个配置文件细节上不尽相同，但是都没有配置关于非中国ip的route rule；为何在透明代理和socks模式下的行为逻辑不同呢

**Comment by Fangliding** [comment]
xray不支持转发ip层数据
