### ISSUE TITLE
客户端出站vmess+tcp+tls   服务器入站vmess+tcp+tls.   连接失败，附带配置，求高人指点迷津。

### ISSUE THREAD

**Issue by cppbeliever** [XTLS/Xray-examples#171]
这是服务器的配置(服务器入站配置)。
```
{
  "port": 443,
  "protocol": "vless",
  "settings": {
    "clients": [
      {
        "id": "ddd", // 填写你的 UUID
        "flow": "xtls-rprx-vision",
        "level": 0,
        "email": "ddin@yourdomain.com"
      }
    ],
    "decryption": "none",
    "fallbacks": [
      {
        "dest": 8080 // 默认回落到防探测的代理
      },
      {
        "path": "/vmesstcp", // 必须换成自定义的 PATH
        "dest": 2345,
        "xver": 1
     }
    ]
  },
  "streamSettings": {
    "network": "tcp",
    "security": "tls",
    "tlsSettings": {
      "alpn": "http/1.1",
      "certificates": [
        {
          "certificateFile": "/home/jamin/xray_cert/xray.crt",
          "keyFile": "/home/jamin/xray_cert/xray.key"
        }
      ]
    }
  }
},
{
"port": 2345,
"listen": "127.0.0.1",
"protocol": "vmess",
"settings": {
    "clients": [
      {
        "id":"dddd", // 填写你的 UUID
        "level": 0,
        "email": "ddddmin@yourdomain.com"
      }
     ]
   },

   "streamSettings": {
            "network": "tcp",
            "security": "none",
   "tlsSettings": {
             "certificates": [
                {
                    "certificateFile": "/home/jamin/xray_cert/xray.crt",
                     "keyFile": "/home/jamin/xray_cert/xray.key"
                }
             ]
           },
            "tcpSettings": {
                "acceptProxyProtocol": true,
                "header": {
                    "type": "http",
                    "request": {
                        "path": [
                            "/vmesstcp" // It must be replaced with a custom PATH, which needs to be consistent with the shunt
                        ]
                    }
                }
            }
        }
  },
```
这是我的客户端配置(客户端出站配置)：
```
{
        "tag": "other",
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "xxxxx", // 换成你的域名或服务器 IP（发起请求时无需解析域名了）
                    "port": 443,
                    "users": [
                        {
                            "id": "xxxx", // 填写你的 UUID
                            "security": "none",
                            "level": 0
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "tcp",
            "security": "tls",
            "tlsSettings": {
                "serverName": "xxxx" // 换成你的域名
            },
            "tcpSettings": {
                "header": {
                    "type": "http",
                    "request": {
                        "path": [
                            "/vmesstcp" // 必须换成自定义的 PATH，需要和服务端的一致
                        ]
                    }
                }
            }
        }
    }
```

服务器配置中非常非常奇怪的是"security"的值必须是“none”客户端就能连接到服务器。如果"security"的值是"tls"客户端就不能连到服务器， 求高人指点 ，先谢谢了。

**Comment by cppbeliever** [comment]
@5e2t  上面的服务器配置是回落后的配置，所以tcp setting里面必须有path，这样和回落匹配。

**Comment by cppbeliever** [comment]
@5e2t  我的服务器是根据xray的小小白白话文做的 ，这样说的话，xray前面确实有个nginx

**Comment by cppbeliever** [comment]
> @cppbeliever 你的web服务器配置证书提供TLS了，反代了xray，web服务器向xray 发起连接时，用的是HTTP而非HTTPS。

我是小白，没彻底明白，可以说得详细点么？谢谢了

**Comment by cppbeliever** [comment]
> @cppbeliever 反向代理服务器回源时，可以用HTTP ，也可以用HTTPS，都可以改。 就是策略问题而已，但你这是纯粹在本机上进行的操作，是完全没有必要在回源时再开TLS的。

我的客户端配置是在我自己的电脑上，服务器配置在远程vps上，不是本机上的操作

**Comment by cppbeliever** [comment]
```
{
  "port": 443,
  "protocol": "vless",
  "settings": {
    "clients": [
      {
        "id": "ddd", // 填写你的 UUID
        "flow": "xtls-rprx-vision",
        "level": 0,
        "email": "ddin@yourdomain.com"
      }
    ],
    "decryption": "none",
    "fallbacks": [
      {
        "dest": 8080 // 默认回落到防探测的代理
      },
      {
        "path": "/vmesstcp", // 必须换成自定义的 PATH
        "dest": 2345,
        "xver": 1
     }
    ]
  },
  "streamSettings": {
    "network": "tcp",
    "security": "tls",
    "tlsSettings": {
      "alpn": "http/1.1",
      "certificates": [
        {
          "certificateFile": "/home/jamin/xray_cert/xray.crt",
          "keyFile": "/home/jamin/xray_cert/xray.key"
        }
      ]
    }
  }
},
{
"port": 2345,
"listen": "127.0.0.1",
"protocol": "vmess",
"settings": {
    "clients": [
      {
        "id":"dddd", // 填写你的 UUID
        "level": 0,
        "email": "ddddmin@yourdomain.com"
      }
     ]
   },

   "streamSettings": {
            "network": "tcp",
            "security": "none",
   "tlsSettings": {
             "certificates": [
                {
                    "certificateFile": "/home/jamin/xray_cert/xray.crt",
                     "keyFile": "/home/jamin/xray_cert/xray.key"
                }
             ]
           },
            "tcpSettings": {
                "acceptProxyProtocol": true,
                "header": {
                    "type": "http",
                    "request": {
                        "path": [
                            "/vmesstcp" // It must be replaced with a custom PATH, which needs to be consistent with the shunt
                        ]
                    }
                }
            }
        }
  },
```

这是我完整的服务器配置。在443端口监听，然后vmess协议回落到本地2345端口

**Comment by CosecantNeko** [comment]
![图片](https://github.com/XTLS/Xray-examples/assets/139856279/0a2e2505-b43d-4049-806d-a21ef9a9b25b)
你的流量在 Nginx 被加上了 TLS，所以 xray 不需要配置 TLS

**Comment by cppbeliever** [comment]
意思就是说，我的xray客户端连接 的是vps的443端口，这样的话，xray客户端的数据就必然首先达到vps的nginx，然后才能达到xray服务器？

**Comment by CosecantNeko** [comment]
![图片](https://github.com/XTLS/Xray-examples/assets/139856279/00f2bfbc-63ae-4b7a-8195-819a282d92b6)

**Comment by CosecantNeko** [comment]
你代理流量是从上面那根 TLS 管子中的 HTTP 管子里进去的

**Comment by cppbeliever** [comment]
> 你代理流量是从上面那根 TLS 管子中的 HTTP 管子里进去的

我的xray客户端是用的vmess+tcp+tls，没用http

**Comment by cppbeliever** [comment]
> > 意思就是说，我的xray客户端连接 的是vps的443端口，这样的话，xray客户端的数据就必然首先达到vps的nginx，然后才能达到xray服务器？
> 
> 我画那张图的时候还没看到你刚发的配置 你的 TLS 是 XRAY 中 vless 入站提供的

如果我把xray服务器的vless入站的security设置成none，那么在vmess中security设置tls是不是就ok了?

**Comment by CosecantNeko** [comment]
你想要做个什么样的东西？

**Comment by cppbeliever** [comment]
> @cppbeliever 不管vless是否提供tls，vless始终使用 HTTP回源，所以给vmess配证书还是用不了

意思就是说xray服务器经过path回落，那么一定用的http,而http是用不了tls的，是这样理解吗？

**Comment by cppbeliever** [comment]
> 你想要做个什么样的东西？ 外层是 TLS 流量的代理协议？

我想做的是，xray客户端是vmess+tcp+tls, xray服务器主入口是在443端口上监听vless协议，如果收到客户端的vmess协议就回落到xray服务器的2345端口，

**Comment by cppbeliever** [comment]
哎，我太失败了，挫败感好强啊，，，，，你们说的，我完全懵逼，xray都快研究了21天了。

**Comment by CosecantNeko** [comment]
能不能让 vmess+tcp+tls 直接处理 443？
为什么非要通过 vless

**Comment by CosecantNeko** [comment]
你外层已经有 TLS 加密保证传输层安全了
为什么要用 vmess 额外加密一次？

**Comment by cppbeliever** [comment]
> 你外层已经有 TLS 加密保证传输层安全了 为什么要用 vmess 额外加密一次？ 直接用 vless + tcp + vision + tls 岂不是更快？

这话我听进去了 谢谢

**Comment by CosecantNeko** [comment]
我理解你的需求了
你希望 443 端口上同时能处理 vless 和 vmess 并且同时开启 TLS 加密对吗？

**Comment by cppbeliever** [comment]
> > @cppbeliever 所以你服务器 的security 为 none 没有任何问题。

我就是看到xray-examples中有个例子， vmess+tcp+tls 我看到服务器端的配置里有security:tls

**Comment by cppbeliever** [comment]
> 我理解你的需求了 你希望 443 端口上同时能处理 vless 和 vmess 并且同时开启 TLS 加密对吗？

对，我以为xray服务器的配置中vmess 协议的security:tls是解密，结果原来是再进行一次加密

**Comment by cppbeliever** [comment]
> > 你外层已经有 TLS 加密保证传输层安全了 为什么要用 vmess 额外加密一次？ 直接用 vless + tcp + vision + tls 岂不是更快？
> 
> 这话我听进去了 谢谢

我以为是服务器这里配置security:tls是解密，结果是再一次加密。

**Comment by CosecantNeko** [comment]
如果你都想开启 TLS 的话
在非 443 端口做一个 vmess + tcp + tls 的代理
然后在 443 端口做一个 vless + vision + reality，dest 写 localhost: vmess 端口上

此时 当 443 端口收到 reality 流量时，xray 直接处理
如果不是 reality 流量，xray 将会像一个端口转发一样转发到 dest 上

**Comment by CosecantNeko** [comment]
请注意，vmess + tcp + tls 可能存在 tit 特征
这可能导致你的服务器被防火墙识别

**Comment by cppbeliever** [comment]
> dest 写 localhost: vmess 端口上

目前用哪个方案最安全

**Comment by cppbeliever** [comment]
xray服务器在443端口和非443端口上监听，有什么区别？

**Comment by cppbeliever** [comment]
https://github.com/XTLS/Xray-examples/blob/main/VMess-TCP-TLS/config_server.json
这个服务器配置中，"security": "tls" 的作用是在服务器端对客户端发来的流量再次tls加密么？

**Comment by cppbeliever** [comment]
@5e2t  @CosecantNeko 
xray客户端的出站中的"security": "tls" 是表示xray客户端通过tls加密数据，发给xray服务器端？
xray服务器端的入站中的"security": "tls" 是什么作用呢？ 是再次加密吗？

**Comment by cppbeliever** [comment]
> @cppbeliever 入站配置tls 是给数据包 去掉tls，出站配置tls是给数据包加上tls

我的xray服务器入站配置中，是不是在vless(vless配置了tls)那里就给数据包去掉了tls加密? 然后vless回落到vmess因为走的http协议，所以在vmess那里加tls(因为tls和https相关)也没用。可以这样理解吗？

**Comment by cppbeliever** [comment]
> @cppbeliever 入站配置tls 是给数据包 去掉tls，出站配置tls是给数据包加上tls

大哥，这个信息很重要，我能理解了，我看文档上没有说这些，只能通过看代码吗？

**Comment by cppbeliever** [comment]
@5e2t @CosecantNeko  谢谢两位大哥，我懂了。

**Comment by cppbeliever** [comment]
> @cppbeliever 当然，需要安装根证书才行~

是的，肯定要服务器的证书。你在xray的tg交流群吗？ 可以拉我进去么？现在进不去那个群了。

**Comment by cppbeliever** [comment]
在人类的线粒体中，下列哪条mRNA不编码 精氨酸-缬氨酸
CGGGUA CGAGUG CGUGUG AGAGUA CGCGUC CGYGUU

回答错误，把我给踢出来了。我去，我还是问的chatgpt。

**Comment by Fangliding** [comment]
@cppbeliever chatgpt能答对就有鬼了 你觉着这玩意知道很多 大多数时候在瞎掰扯（）

**Comment by CosecantNeko** [comment]
试了一下
10 分钟刚好能找到答案

解题思路
1. 提取关键词 Google 搜索 search?q=人类 线粒体 mRNA 编码 缬氨酸
2. 寻找有关条目，进入条目后使用 CTRL + F 寻找关键词
3. 阅读关键词上下文 推理出答案

当你的 XRAY 令你 confuse 的时候
也可以这样解决

**Comment by ischub** [comment]
@CosecantNeko 服务端 vless+tcp+tls+vmess

**Comment by cppbeliever** [comment]
> 试了一下 10 分钟刚好能找到答案
> 
> 解题思路
> 
> 1. 提取关键词 Google 搜索 search?q=人类 线粒体 mRNA 编码 缬氨酸
> 2. 寻找有关条目，进入条目后使用 CTRL + F 寻找关键词
> 3. 阅读关键词上下文 推理出答案
> 
> 当你的 XRAY 令你 confuse 的时候 也可以这样解决

thanks !very,very.....

**Comment by cppbeliever** [comment]
> @cppbeliever chatgpt能答对就有鬼了 你觉着这玩意知道很多 大多数时候在瞎掰扯（）

哈哈，可以用chatgpt来帮我应付我侄子的诗歌作业。

**Comment by cppbeliever** [comment]
> @cppbeliever 挺好的，风扇 为 普及 人类 对 AI的 本质的了解做出了卓越贡献

是的

**Comment by Fangliding** [comment]
与example无关
