### ISSUE TITLE
VLESS-mKCPSeed服务端配置config_server.json有误

### ISSUE THREAD

**Issue by Benjamin1919** [XTLS/Xray-examples#173]
https://github.com/XTLS/Xray-examples/blob/main/VLESS-mKCPSeed/config_server.json

"mtu""uplinkCapacity""downlinkCapacity""congestion""header"都属于"kcpSettings"的子项，而示例把这些参数都放在了"kcpSettings"的外面

**Comment by Fangliding** [comment]
Fixed
