### ISSUE TITLE
'VLESS-TCP-XTLS-WHATEVER' does not work in XRAY server

### ISSUE THREAD

**Issue by PingshaZoo** [XTLS/Xray-examples#175]
the example config file of 'VLESS-TCP-XTLS-WHATEVER' does not work in XRAY server, and its error info is "please use vless flow "xtls-rprx-vision" with tls or reality."
after modifid the first inbound "xtlssetting" to "tlssetting", it works well.

**Comment by Fangliding** [comment]
Thanks for reporting
It's deprecated
