### ISSUE TITLE
restore 'VLESS-TCP-XTLS-WHATEVER'

### ISSUE THREAD

**Issue by zll600** [XTLS/Xray-examples#180]
`'VLESS-TCP-XTLS-WHATEVER'` is used by https://github.com/XTLS/Xray-docs-next/blob/c9add77895905a9560d65a4e3e5deeced3d8989b/docs/document/level-1/fallbacks-lv1.md?plain=1#L134 now.

But it was removed by https://github.com/XTLS/Xray-examples/commit/ecefc32120d6e1bd778c6becb8f84e06b9180ac9#diff-03f92c83b3e31ef884b2074eee3d1103a69934d4bb882d0f852d808f9fab4f90 because https://github.com/XTLS/Xray-examples/issues/175.

Can these files be restored? I can create a PR.

**Comment by Fangliding** [comment]
I'd like to remove broken link in docs.
Putting all these protocols into one port is no longer a recommended usage.
