### ISSUE TITLE
Remove Content Based Package Restrictions?

### ISSUE THREAD

**Issue by maxy1** [XTLS/Xray-examples#181]
Hi, Can you please tell me how to remove Content Based Package restrictions using xray ?
For example we have zoom packages with unlimited data. People use zoom.us as the SNI to bypass the traffic with tls and allowinsecure checked. I think they are using Xray and revers proxy to achieve this. I have been trying to find good configuration for past two weeks none is successful. ( it's mainly due to lack of my knowledge and understanding. ).
if you can give me bit of clues example configuration I really appreciate.

**Comment by Fangliding** [comment]
maybe filter by IP
