### ISSUE TITLE
All-in-One-fallbacks-Nginx • gRPC not working

### ISSUE THREAD

**Issue by dugong-lewat** [XTLS/Xray-examples#183]
the Xray version is getting updated but why is the gRPC all-in-one not working properly, even though the previous Xray version can run properly (I forgot what version of Xray) I am still using the exact same configuration with this

**Comment by Fangliding** [comment]
Changing the core version is an easy thing, at least test which version and provide feedback after encountering problems

**Comment by Fangliding** [comment]
close as no response
