### ISSUE TITLE
Slow speed of TLS varients

### ISSUE THREAD

**Issue by mohammadne** [XTLS/Xray-examples#185]
In my case [VLESS-TCP](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP) works very  well but the TLS versions like [VLESS-TCP-TLS](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS), [VLESS-TCP-XTLS-Vision-REALITY](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision-REALITY), [VLESS-TCP-XTLS-Vision](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision) and etc all works but the speed is very very low and I don't know what's the problem.
As I'm new to the xray, I would be thankful if you could help me to resolve the issue.
i.e I don't know when non-encrypted version works well, why the TLS version is very slow (~90 mb/s vs 2mb/s).

Thanks in advance

**Comment by Fangliding** [comment]
Some local ISP may interfere TLS connection, not our problem
