### ISSUE TITLE
vless+xtls网站浏览不稳定有时能打开有时就报连接超时

### ISSUE THREAD

**Issue by bruce2k** [XTLS/Xray-examples#19]
根据小小白白的指引一步步配置,完成后确实速度比v2ray快，可是访问网站上午能正常打开，下午就报连接超时页面载入出错。油管倒是每次都能打开，可视频大部分都不能正常播放，只有很少能正常播放的，求解惑！配置如下：
服务器端：
{
    "log": {
        "loglevel": "warning",    
        "access": "/xx/xx/xx/access.log",    
        "error": "/xx/xx/xx/error.log"  
    },
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",   
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private" 
                ],
                "outboundTag": "block" 
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all" 
                ],
                "outboundTag": "block"   
            }
        ]
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "ubuntu@domain.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8080 
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "allowInsecure": false,
                    "minVersion": "1.2", 
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/xx/xx/xray.crt",
                            "keyFile": "/xx/xx/xray.key"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}

客户端：
{
    "log": {
        "access": "/xx/xx/access.log",
        "error": "/xx/xx/error.log",
        "loglevel": "warning" 
    },
       
    "dns": {
        "servers": [
            {
                "address": "1.1.1.1",
                "domains": [
                    "geosite:geolocation-!cn"
                ]
            },
            {
                "address": "223.5.5.5",
                "domains": [
                    "geosite:cn"
                ],
                "expectIPs": [
                    "geoip:cn"
                ]
            },
            {
                "address": "114.114.114.114",
                "domains": [
                    "geosite:cn"
                ]
            },
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:geolocation-!cn"
                ],
                "outboundTag": "proxy"
            }
        ]
    },

    "inbounds": [
        {
            "tag": "socks-in",
            "protocol": "socks",
            "listen": "127.0.0.1",   
            "port": 1080,
            "settings": {
                "udp": true
            }
        },
        {
            "tag": "http-in",
            "protocol": "http",
            "listen": "127.0.0.1",
            "port": 1081 
        }
    ],
       
    "outbounds": [
        {
            "tag": "proxy",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "www.mydomain.com",
                        "port": 443,
                        "users": [
                            {
                                "id": "uuid", 
                                "flow": "xtls-rprx-splice", 
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "serverName": "www.mydomain.com", 
                    "allowInsecure": false  
                }
            }
        },

        {
            "tag": "direct",
            "protocol": "freedom"
        },

        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]    
}
客户端日志
2021/03/07 22:16:21 tcp:127.0.0.1:51956 rejected  proxy/socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:51956: read: connection reset by peer
2021/03/07 22:16:21 tcp:127.0.0.1:51962 accepted tcp:42.49.13.10:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51958 accepted tcp:42.49.13.10:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51960 accepted tcp:42.49.13.10:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51970 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51976 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51974 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51990 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51986 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51984 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51988 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51982 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:51992 accepted tcp:42.49.13.6:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52008 rejected  proxy/socks: insufficient header > EOF
2021/03/07 22:16:21 tcp:127.0.0.1:52020 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52010 accepted tcp:42.49.13.5:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52012 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52014 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52016 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52024 accepted tcp:42.49.13.5:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52018 accepted tcp:42.49.13.7:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52022 accepted tcp:42.49.13.5:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52046 rejected  proxy/socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:52046: read: connection reset by peer
2021/03/07 22:16:21 tcp:127.0.0.1:52044 accepted tcp:104.26.6.142:443 [socks-in >> proxy]
2021/03/07 22:16:21 tcp:127.0.0.1:52048 accepted tcp:39.96.132.69:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52056 accepted tcp:58.20.147.88:80 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52054 accepted tcp:58.20.147.88:80 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52062 accepted tcp:58.20.147.88:80 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52066 accepted tcp:39.107.11.172:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52070 accepted tcp:110.52.196.231:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52074 accepted tcp:42.49.13.5:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52078 accepted tcp:111.206.209.249:443 [socks-in -> direct]
2021/03/07 22:16:21 tcp:127.0.0.1:52082 rejected  proxy/socks: failed to read request > EOF

**Comment by bruce2k** [comment]
aaa

**Comment by Fangliding** [comment]
线路问题
