### ISSUE TITLE
应当如何选择协议组合？

### ISSUE THREAD

**Issue by Alceatraz** [XTLS/Xray-examples#194]
请问：XRay的协议/传输/安全这三者有无推荐组合，类似于“最佳实践”“不切实际”“最隐蔽”“速度最快”“延迟最低”等？

比如
1：Vless + vision + TCP+TLS 作为招牌推荐，实际上在很多移动的网络环境中是无法访问的。
2：Vless 在非 TCPTLS 中vision是否还有效？同时引出VMess + KCP + NONE 和 Vless + KCP + TLS 哪个更优？

这样的问题会有很多，请问有无对比表格类的文档

**Comment by Fangliding** [comment]
这样的对比表格大概是没有的 每个协议的特点可以看看对应的介绍
剩下两个问题可以回答一下
1 一句无法访问没有任何用
2 vision必须要TCP+TLS/reality 文档有写 还有KCP别用
