### ISSUE TITLE
VLESS-TCP-REALITY (without being stolen) 配置问题

### ISSUE THREAD

**Issue by 328902301** [XTLS/Xray-examples#202]
测试仓库提供的 VLESS-TCP-REALITY (without being stolen) 配置，xray 内核是最新版本v24.11.11，配置文档除了添加对应的参数，其他未改。

请求数据进入服务器后路由，只能匹配到第二条规则，也就是被 block 了，除非访问 dest 的域名才能匹配第一条规则。

**Comment by Fangliding** [comment]
![image](https://github.com/user-attachments/assets/eeef154c-2bf3-4bc9-a014-ac7f970b5cfc)
这里的两条规则都是指定了inboundTag才会匹配上的 vless入站都没tag怎么可能被匹配上
