### ISSUE TITLE
How  to implement VLESS-XHTTP3-Nginx with Caddy | 如何用Caddy 实现 vless-xhttp3

### ISSUE THREAD

**Issue by 1orz** [XTLS/Xray-examples#205]
如题 如何用Caddy 实现 VLESS-XHTTP3 ？在 [XTLS/Xray-examples](https://github.com/XTLS/Xray-examples)中，示例配置文件[这里](https://github.com/XTLS/Xray-examples/tree/main/VLESS-XHTTP3-Nginx)只有Nginx实现配置方法。那么 Caddy 怎么实现？ 看[文档](https://xtls.github.io/config/transports/xhttp.html) 写的很少，没思路了，求大佬指点

**Comment by Fangliding** [comment]
之前HTTP的旧模板改一下应该能用

**Comment by xqzr** [comment]
~~可以~~看看 https://t.me/projectXray/4137875
