### ISSUE TITLE
debain 安装trojan 服务器失败 

### ISSUE THREAD

**Issue by pertance** [XTLS/Xray-examples#26]
大佬按您的配置 在服务器安装trojan 更改配置文件后 xray 无法启动 
failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build TLS config. > infr

在安装xray 的时候 有个提示 操作系统 版本过低 跟这个有关系么

**Comment by JimhHan** [comment]
配置文件错误。

注：可以按右➡️方向键看完整日志，

**Comment by pertance** [comment]
好我再重新检查一下,完全按您配置走的 就改了个密码 和路径

**Comment by pertance** [comment]
解析证书错误  没证书  申请证书前 xray不能启动么？我申请证书一直失败

**Comment by JimhHan** [comment]
您的日志不全，无法分析。

> 注：可以按右➡️方向键看完整日志

**Comment by pertance** [comment]
这个是错误日志
: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /usr/local/etc/xray/cert/cert.crt: no such
tatus=23/n/a

这个是证书申请的错误
Verify error:Invalid response from http://xx.xxxx.ml/.well-known/acme-challenge/k4BkFCjFHb99iV7YbmYlFVQVYNoAvQnK_O1Z3R2k__g

**Comment by pertance** [comment]
啊 我不明白 什么意思这是

**Comment by Fangliding** [comment]
没有证书
