### ISSUE TITLE
对于bittorrent的配置是放在rule前面还是后面好

### ISSUE THREAD

**Issue by chanhsiaoyu** [XTLS/Xray-examples#29]
在家里配的透明代理，由于经常做bt下载，所以关心bittorrent协议的配置。
看例子里好像都没有，又看说明中说rule是从上到下匹配的，那么是不是把相关配置放在第一位对性能最好？

**Comment by geniusyjiang** [comment]
个人经验感觉iptables端口或ip放行效果好点，v2ray和xray内拦截bt协议效果都不咋样

**Comment by chika0801** [comment]
透明代理呀，你自己写配置，不是用如passwall1吧。那肯定是放最上面，先上bt的直连出站

**Comment by yuhan6665** [comment]
close as solved
