### ISSUE TITLE
有没有支持 http2 的 xlts 配置

### ISSUE THREAD

**Issue by andy7z** [XTLS/Xray-examples#31]
目前是 VLESS + XLTS 回落 Nginx:80, 性能十分强劲, 期望能让 fallback 支持 http2

**Comment by 97xiami** [comment]
"fallbacks": [
          {
            "apln": "h2",
            "dest": 80
          }
]


"streamSettings": {
          "alpn": [
            "h2"
          ]
}

**Comment by chika0801** [comment]
我的 https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS
