### ISSUE TITLE
请问一下回落机制能把ssh和网页分开吗？

### ISSUE THREAD

**Issue by HaoKunT** [XTLS/Xray-examples#32]
就是想通过xray的回落机制把ssh协议和https协议分开，分到不同的端口上去，这样自己搭的gitlab就可以复用一个端口了。看了例子，感觉不是太会，没弄明白那个`path`是什么意思，像`ssh`这种协议也没有`path`这个说法。

**Comment by hmol233** [comment]
@HaoKunT 您好，http 和 ssh 就应该是两个端口。close.
