### ISSUE TITLE
如何在Shadowsocks-2022的json里配置DNS服务器

### ISSUE THREAD

**Issue by sophauer** [XTLS/Xray-examples#57]
as tittle,
如何在Shadowsocks-2022的json里配置指定DNS服务器.
我用ss的nameserver配置,貌似不行.
求赐教

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/Shadowsocks-2022-TCP/config_server.json

**Comment by sophauer** [comment]
> https://github.com/chika0801/Xray-examples/blob/main/Shadowsocks-2022-TCP/config_server.json

谢谢,但我配置起来并不行.
服务器缺省DNS是1.1.1.1
我期待的是配置Shadowsocks-2022的DNS指向208.67.220.123(过滤掉成人内容)
但server.json配置段这样配置
`"dns": {
        "servers": [
            "208.67.222.123,208.67.220.123"
        ],
        "queryStrategy": "UseIPv4"
    },`

是无效的.Xraycore是直接从source编译出来的最新版本

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/97fb8e322d9ec0cdc1779bb65e17808e55bf761f/Shadowsocks-2022-TCP/config_server.json#L49

出站那要加 useipv4

**Comment by sophauer** [comment]
hi
12万分感谢,
已解决
