### ISSUE TITLE
Shadowsocks 2022多用户客户端配置密码貌似有误

### ISSUE THREAD

**Issue by charliez0** [XTLS/Xray-examples#59]
Failed to start: main: failed to create server > proxy/shadowsocks_2022: create method > invalid argument

**Comment by charliez0** [comment]
@RPRX

**Comment by yuhan6665** [comment]
试试 1.5.9 如果还有问题 需要提供配置和更全的出错日志

**Comment by jantacy** [comment]
{
  "inbounds": [
    {
      "port": 10801,
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    },
    {
      "port": 10802,
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "{{ host1 }}",
            "port": 1234,
            "method": "2022-blake3-aes-128-gcm",
            "password": "{{ server psk }}:{{ user psk }}"
          },
          {
            "address": "{{ host2 }}",
            "port": 1234,
            "method": "2022-blake3-aes-128-gcm",
            "password": "{{ server psk }}:{{ user psk }}"
          }
        ]
      }
    }
  ]
}

> 试试 1.5.9 如果还有问题 需要提供配置和更全的出错日志

1.5.10 只配置一个(host)正常，多服务器则直接闪退，windows环境，未使用UI客户端。

**Comment by yuhan6665** [comment]
@jantacy 老的多服务器负载均衡不好使了 用 routing 里面的 balancer
