### ISSUE TITLE
按VLESS-TCP-TLS-WS 样例配置，如启用CDN ，是否端口只能443？

### ISSUE THREAD

**Issue by chinacaoxy** [XTLS/Xray-examples#6]
按VLESS-TCP-TLS-WS 样例配置，如启用CDN ，是否端口只能443？

**Comment by smallbeeking** [comment]
> 按VLESS-TCP-TLS-WS 样例配置，如启用CDN ，是否端口只能443？

入使用cloudflare，详见：
https://support.cloudflare.com/hc/zh-cn/articles/200169156

**Comment by chinacaoxy** [comment]
Thanks.
