### ISSUE TITLE
Vless tcp fallback to vmess tcp 无法连接 

### ISSUE THREAD

**Issue by jinwyp** [XTLS/Xray-examples#66]
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

按照上面这个教程 

Vless tcp fallback to vmess tcp and vmess ws 

vmess ws 是可以正常工作的， 但vmess 的 tcp 里面带path /vmesstcp 就无法连接

用脚本 ``` bash <(curl -Lso- https://git.io/oneclick) ``` 安装选13 就可以安装 vless fallback to vmess tcp  可以重现问题

印象中以前是可以的，不知道哪个版本后就不行了

**Comment by chika0801** [comment]
可参考我的模板
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS

**Comment by jinwyp** [comment]
> 可参考我的模板 https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS

你这里没有vmess tcp 啊

**Comment by chika0801** [comment]
> > 可参考我的模板 https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS
> 
> 你这里没有vmess tcp 啊

我是开的vmess ws tls,不是 vmess ws.

vmess tcp 你去隔壁看看
https://github.com/v2fly/v2ray-examples/tree/master/VMess-TCP

**Comment by jinwyp** [comment]
> 

我说的是vless tls tcp fallback to vmess tls tcp

**Comment by chika0801** [comment]
> > 
> 
> 我说的是vless tls tcp fallback to vmess tls tcp

你参考我发的模板自己改改了

**Comment by jinwyp** [comment]
> 

你根本没看懂， 你的模板也有错误， 你看看下面的范例吧
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

**Comment by chika0801** [comment]
好久没有提vmess tcp tls，去隔壁看了下有这模板配置2333 建议你不用这vmess tcp tls远古组合2333

**Comment by chika0801** [comment]
> > 
> 
> 你根本没看懂， 你的模板也有错误， 你看看下面的范例吧 https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

没有哦，我自己都在用2333

**Comment by chika0801** [comment]
> > 
> 
> 你根本没看懂， 你的模板也有错误， 你看看下面的范例吧 https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

我就得抄的官方的，自己改了改

**Comment by jinwyp** [comment]
> > > 
> > 
> > 
> > 你根本没看懂， 你的模板也有错误， 你看看下面的范例吧 https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json
> 
> 没有哦，我自己都在用2333

你不懂，你知道你配置有错误吗？ 能连接不等于没错误， 你要知道配置每行的意思

我说问题就是这个官方范例以前是可以的，现在不行了。 
你的配置中 不需要nginx 的h2 ， 还有xray也不需要fallback h2的trojan

**Comment by chika0801** [comment]
> > > > 
> > > 
> > > 
> > > 你根本没看懂， 你的模板也有错误， 你看看下面的范例吧 https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json
> > 
> > 
> > 没有哦，我自己都在用2333
> 
> 你不懂，你知道你配置有错误吗？ 能连接不等于没错误， 你要知道配置每行的意思
> 
> 我说问题就是这个官方范例以前是可以的，现在不行了。 你的配置中 不需要nginx 的h2 ， 还有xray也不需要fallback h2的trojan

h2的trojan 不写这个，在客户端要指定。h2 不然连不上，你想教客户选h2，不在服务器配置上加也行（我试了）

**Comment by chika0801** [comment]
你用官方的，原来行现在不行，帮不了你不好意思

**Comment by jinwyp** [comment]
> 

用脚本 bash <(curl -Lso- https://git.io/oneclick) 安装选17 装一下 vless tcp tls fallback to xray的trojan  看以下配置 不用h2 也不用客户端设置h2 

h2 是有其他需求 专门针对h2 的协议才需要使用。

**Comment by jinwyp** [comment]
> 

的确是这个问题 服务器端配置了 伪装类型 为 http ,  而客户端的生成的配置漏了


这里还需要注意的几点

查看文档  https://www.v2fly.org/config/transport/tcp.html#tcpobject
有一句话 ：

>> 数据包头部伪装设置，默认值为 NoneHeaderObject。HTTP 伪装无法被其它 HTTP 服务器（如 Nginx）分流，但可以被 VLESS fallbacks path 分流。


注意1 当只使用Vmess Tcp时 伪装类型 "type": "none"  也可以正常工作， 所以无论是 无加密的Vmess Tcp 或有TLS 的nginx 443 + vmess tcp 都可以用 伪装类型 "type": "none" .  这也是之前这个问题被忽略的原因

注意2 如果使用 vless fallback to vmess tcp  必须使用 伪装类型 "type": "http" ， 使用伪装类型 "type": "none" 无法正常工作。 所以服务器和客户端 必须都配置 伪装类型 "type": "http" 。相当于这个参数是专门配合 vless fallback 使用的

感谢楼上找出问题。
