### ISSUE TITLE
用例子里的shadowsocks 2022中转配置，只能连接到中转机

### ISSUE THREAD

**Issue by ymcoming** [XTLS/Xray-examples#67]
按照服务器与客户端的配置，能连接上，但通过测试IP，发现还是中转机的IP，而不是落地机的IP 

中转机配置：

       {
            "port": 1234,
            "protocol": "shadowsocks",
            "settings": {
                "method": "2022-blake3-aes-128-gcm",
                "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
                "clients": [
                    {
                        "address": "11.22.33.44",  ---落地机IP
                        "port": 5678,
                        "password": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=",
                        "email": "yy@email.com"
                    }
                ],
                "network": "tcp,udp"
            }
        }

落地机配置 ：

        {
            "port": 5678,
            "protocol": "shadowsocks",
            "settings": {
                "method": "2022-blake3-aes-128-gcm",
                "password": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=",
                "network": "tcp,udp"
            }
        }

客户端配置：

    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "中转机IP",
            "port": 1234,
            "method": "2022-blake3-aes-128-gcm",
            "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="
          }
        ]
      }
    }

**Comment by chika0801** [comment]
发下中转和落地的配置文件

**Comment by wawnnzxd** [comment]
> 发下中转和落地的配置文件

也是同样的问题，

服务端 JSON (中转)

{
  "inbounds": [
    {
      "port": 1234,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "{{ relay psk }}",
        "clients": [
          {
            "address": "server",
            "port": 1234,
            "password": "{{ server/user psk }}", /////这一段没有太明白，是server和user的psk都要写进去吗，但是按照这个格式写进去就会报错呀，比如些 "password": "bftgOHCcwfoMM/aa5Q0eGg==/SKCqQ4rsiJCZxDFAQPwOoA==", 写了之后就会立刻报错
            "email": "my server"
          }
        ],
        "network": "tcp,udp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}

**Comment by chika0801** [comment]
中转机
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
省略你的入站配置
    "outbounds": [
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "落地机IP",
                        "port": 60000,
                        "method": "2022-blake3-aes-128-gcm",
                        "password": "密码123456:密码123456"
                    }
                ]
            }
        }
    ]
}
```

落地机
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 60000,
            "protocol": "shadowsocks",
            "settings": {
                "method": "2022-blake3-aes-128-gcm",
                "password": "密码123456",
                "clients": [
                    {
                        "address": "",
                        "port": 60000,
                        "password": "密码123456"
                    }
                ],
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```

**Comment by chika0801** [comment]
建议你把中转机和落地机，密码都用一样的，最简单

**Comment by chika0801** [comment]
> 按照服务器与客户端的配置，能连接上，但通过测试IP，发现还是中转机的IP，而不是落地机的IP
> 
> 中转机配置：
> 
> ```
>    {
>         "port": 1234,
>         "protocol": "shadowsocks",
>         "settings": {
>             "method": "2022-blake3-aes-128-gcm",
>             "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
>             "clients": [
>                 {
>                     "address": "11.22.33.44",  ---落地机IP
>                     "port": 5678,
>                     "password": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=",
>                     "email": "yy@email.com"
>                 }
>             ],
>             "network": "tcp,udp"
>         }
>     }
> ```
> 
> 落地机配置 ：
> 
> ```
>     {
>         "port": 5678,
>         "protocol": "shadowsocks",
>         "settings": {
>             "method": "2022-blake3-aes-128-gcm",
>             "password": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=",
>             "network": "tcp,udp"
>         }
>     }
> ```
> 
> 客户端配置：
> 
> ```
> {
>   "protocol": "shadowsocks",
>   "settings": {
>     "servers": [
>       {
>         "address": "中转机IP",
>         "port": 1234,
>         "method": "2022-blake3-aes-128-gcm",
>         "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="
>       }
>     ]
>   }
> }
> ```

看我上面的示例

**Comment by wawnnzxd** [comment]
仔细看了发现问题所在，中转机和落地机的配置全都写在inbounds里了，还以为是这个逻辑，1通过ss的ip和密码直接连上👉2，然后客户端直接连1， 没有注意到1机器配置要写在outbounds里面。。。。😂

**Comment by chika0801** [comment]
> 仔细看了发现问题所在，中转机和落地机的配置全都写在inbounds里了，还以为是这个逻辑，1通过ss的ip和密码直接连上👉2，然后客户端直接连1， 没有注意到1机器配置要写在outbounds里面。。。。😂 感谢大佬深夜的回复，我也是折腾了半天和上面的跟门一样思考的逻辑，所以直接线路不通了，我还是乖乖1机器gost端口转发方式来和2机器通讯吧，这样简单一些，😂

我的中转到落地用的ss2022这种方法，我喜欢就一个xray core搞定

**Comment by ymcoming** [comment]
Chika0801的方法不符合example中转配置的原意,原意就是inbounds去中转多个站点,你用outbounds那节点要么定死,要么冗长。

比如我有个IPLC出口准备拉万物,拉甲骨文韩/日/新加坡/印/美各节点、拉virmuch等节点。如果example中转配置可行,那么inbounds只需一个端口配以各落地机(可能十几台机)就行了,很简洁。

但如果outbounds来做,明显十几台机就要配十几个分流配置,过于冗长,路由切向也麻烦,还不如gost完成

**Comment by chika0801** [comment]
我看了下更新日志，提供的示例，和开发文档https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-2-shadowsocks-2022-extensible-identity-headers.md#scenarios

重新看了你1楼帖的配置，我也测试了一下，确实中转失败，配了得到的IP是中转机的

**Comment by chika0801** [comment]
@nekohasekai @yuhan6665 麻烦大佬有时间看看，是我们的理解有问题吗

**Comment by yuhan6665** [comment]
想用中转的试试这个 build https://github.com/XTLS/Xray-core/actions/runs/2814430954

**Comment by chika0801** [comment]
> :

感谢你，测试了，这个版本的程序，成功了。

**Comment by yuhan6665** [comment]
也感谢你和 @ymcoming 测试
下个版本修复 先关了

**Comment by chika0801** [comment]
> 也感谢你和 @ymcoming 测试 下个版本修复 先关了

再测试了一下。

客户端是1.5.9。

中转机是今天的测试版。

落地机是1.5.9。

也能中转成功，得到落地机的IP。

**Comment by yatounoneko** [comment]
> 谢谢你和@ymcoming测试 下个版本修复先关了

@yuhan6665 刚尝试了下用你的测试版本确实能中转成功，但似乎也会导致UDP无法中转（Fullcone）
NatTypeTestor显示：UDPBLOCKED
不过这情况我也试过用iptables、socat、realm都无法中转UPD，不知道是不是和shadowsocks 2022的机制有关
