### ISSUE TITLE
98：地址已在使用中

### ISSUE THREAD

**Issue by mhnhh123** [XTLS/Xray-examples#68]
在重启nginx时显示
Aug 15 11:08:19 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/default.sock failed (98: Address already in use)
Aug 15 11:08:19 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/h2c.sock failed (98: Address already in use)
Aug 15 11:08:20 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/default.sock failed (98: Address already in use)
Aug 15 11:08:20 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/h2c.sock failed (98: Address already in use)
Aug 15 11:08:20 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/default.sock failed (98: Address already in use)
Aug 15 11:08:20 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] bind() to unix:/dev/shm/h2c.sock failed (98: Address already in use)
Aug 15 11:08:21 VM-o4SvqT80FlA1 nginx[19610]: nginx: [emerg] still could not bind()
Aug 15 11:08:21 VM-o4SvqT80FlA1 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Aug 15 11:08:21 VM-o4SvqT80FlA1 systemd[1]: nginx.service: Failed with result 'exit-code'.
Aug 15 11:08:21 VM-o4SvqT80FlA1 systemd[1]: Failed to start nginx - high performance web server.
我不知道如何解决它

**Comment by chika0801** [comment]
我是reboot即可 其它方法我也不会

**Comment by Fangliding** [comment]
使用lsof检查
