### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by mhnhh123** [XTLS/Xray-examples#74]
配置文件
{
 "port": 443,
 "protocol": "vmess",
 "settings": {
  "clients": [
   {
    "id": ""
   }
  ]
 },
 "streamSettings": {
  "network": "quic",
  "quicSettings": {},
  "security": "tls",
  "tlsSettings": {
   "certificates": [
    {
     "certificateFile": "fullchain.crt", // 使用真实证书
     "keyFile": "private.key"
    }
   ]
  }
 }
}
报错显示022/08/30 00:18:52 127.0.0.1:57512 accepted //91.108.56.113:443 [http -> proxy]
2022/08/30 00:18:52 127.0.0.1:57511 accepted //mtalk.google.com:5228 [http -> proxy]
2022/08/30 00:18:52 127.0.0.1:57513 accepted http://91.108.56.113:80/api [http -> proxy]
2022/08/30 00:18:53 127.0.0.1:57517 accepted //91.108.56.113:443 [http -> proxy]
2022/08/30 00:18:53 127.0.0.1:57518 accepted http://91.108.56.113:80/api [http -> proxy]
2022/08/30 00:18:55 127.0.0.1:57520 accepted //91.108.56.113:443 [http -> proxy]
2022/08/30 00:18:55 127.0.0.1:57521 accepted http://91.108.56.113:80/api [http -> proxy]
2022/08/30 00:18:56 127.0.0.1:57522 accepted //alive.github.com:443 [http -> proxy]
2022/08/30 00:18:59 127.0.0.1:57524 accepted //91.108.56.113:443 [http -> proxy]
2022/08/30 00:18:59 127.0.0.1:57525 accepted http://91.108.56.113:80/api [http -> proxy]
2022/08/30 00:19:01 127.0.0.1:57527 accepted //alive.github.com:443 [http -> proxy]
2022/08/30 00:19:07 127.0.0.1:57531 accepted //91.108.56.113:443 [http -> proxy]
2022/08/30 00:19:07 127.0.0.1:57532 accepted http://91.108.56.113:80/api [http -> proxy]
2022/08/30 00:19:08 127.0.0.1:57533 accepted //alive.github.com:443 [http -> proxy]

**Comment by chika0801** [comment]
建议换其它端口试试有惊喜
