### ISSUE TITLE
SS22中转方案无法和多用户共存

### ISSUE THREAD

**Issue by wawnnzxd** [XTLS/Xray-examples#75]
假设落地机已配置完毕情况下，中转机配置如下，中转+多用户方案
服务端：
{
    "log": {
        "loglevel": "warning",
        "error": "/var/log/xray/error.log",
        "access": "/var/log/xray/access.log"
    },
    "inbounds": [
    {
      "port": 443,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "n/+qYmhkfhHEkA97wGFo6g==",
        "clients": [
          {
            "address": "103.xxx.xx.xxx",  //落地机中转配置
            "port": 8443,
            "password": "WiHePWePm19g5q1YgndC5A==",
            "email": "myserver@ss22.com"
          },
          {
        "password": "QNtU0NRpw2qadOQzKTM0MQ==", //多用户
        "email": "my user"
          }
    
        ],
        "network": "tcp,udp"
      }
    }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

此时只能获取到中转机IP，无法获取到落地机IP

只能使用这个折中方案才能兼容落地机IP和中转机IP皆可通过ss22连接
{
    "log": {
        "loglevel": "warning",
        "error": "/var/log/xray/error.log",
        "access": "/var/log/xray/access.log"
    },
    "inbounds": [
    {
      "port": 443,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "n/+qYmhkfhHEkA97wGFo6g==",
        "clients": [
          {
            "address": "103.xxx.xx.xxx",   //落地机配置
            "port": 8443,
            "password": "WiHePWePm19g5q1YgndC5A==",
            "email": "myserver@ss22.com"
          }
        ],
        "network": "tcp,udp"
      }
    },
    {
      "port": 8443,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "QNtU0NRpw2qadOQzKTM0MQ==", //中转机配置
        "network": "tcp,udp"
      }
    }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

应该中转配置就是变种的多用户类型呀，是不是哪里不太对😂

**Comment by yuhan6665** [comment]
目前无法共存 中转必须使用单独的端口

**Comment by chika0801** [comment]
> 目前无法共存 中转必须使用单独的端口

我测试时也发现了，就知道这特性了

**Comment by wawnnzxd** [comment]
大哥大姐早上好，1.6.0版本修复了多用户了吗，祝大家平安快乐顺利
