### ISSUE TITLE
有没有apache前置分流到xray的配置。

### ISSUE THREAD

**Issue by lin1123** [XTLS/Xray-examples#77]

**Comment by lxhao61** [comment]
1、apache反代WebSocket参考[V2ray官方资料](https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE)
2、apache反代h2c需要自己配置apache，可参考[我示例中caddy2反代h2c](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2Bh2c)%2Bcaddy)。注意同时启用[mod_http2](https://httpd.apache.org/docs/trunk/mod/mod_http2.html)与[mod_proxy_http2](https://httpd.apache.org/docs/trunk/mod/mod_proxy_http2.html)模块，并正确配置即可。

**Comment by lin1123** [comment]
> 1、Apache反代WebSocket参考[V2ray官方资料中Apache配置](https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE)。 2、Apache反代h2c需要自己配置Apache，可参考[caddy2反代h2c示例原理](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2Bh2c)%2Bcaddy)。注意apache需同时启用[mod_http2](https://httpd.apache.org/docs/2.4/mod/mod_http2.html)与[mod_proxy_http2](https://httpd.apache.org/docs/2.4/mod/mod_proxy_http2.html)模块，并正确配置。

ws与h2、h2c都是通过path路径进行转发的吗？尝试过使用grpc协议，然后用Apache转发，一直无法成功。

**Comment by lxhao61** [comment]
是的。目前Apache应该不支持gRPC协议转发，需要Apache APISIX才能实现转发。
