### ISSUE TITLE
希望能出一个vision搭配回落到nginx

### ISSUE THREAD

**Issue by lssmoon2019** [XTLS/Xray-examples#89]
希望能出一个vision搭配回落到nginx的模板，xray的配置模板和nginx的配置模板

**Comment by chika0801** [comment]
> 希望能出一个vision搭配回落到nginx的模板，xray的配置模板和nginx的配置模板

https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server_fallbacks.json

你参考下没，什么难度一看就懂

**Comment by Portan** [comment]
Https访问会提示ERR_HTTP2_PROTOCOL_ERROR

**Comment by ZqinKing** [comment]
inbounds下setting下添加                "fallbacks":[
                    {
                        "dest":8088
                    },
                    {
                        "alpn":"h2",
                        "dest":8443
                    }
                ]即可。第一个是http的nginx端口，第二个是https的端口
