### ISSUE TITLE
更新1.2.3后VLESS-TCP-XTLS-WHATEVER配置似乎无法用了= =

### ISSUE THREAD

**Issue by shinanzhuomo** [XTLS/Xray-examples#9]
更新1.2.3后VLESS-TCP-XTLS-WHATEVER配置似乎无法用了= = 求教..

**Comment by rprx** [comment]
已知此版本的 fallbacks xver 可能不会生效，https://github.com/XTLS/Xray-core/commit/8ffc43035179964e8472486339b220ffccafed29
