### ISSUE TITLE
请问我是按照VLESS+XTLS+VISION的模板配置的，也把里面的信息换成了自己的，但重启服务后xray直接登不上了，这是怎么回事啊

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-examples#92]
// REFERENCE:
// https://github.com/XTLS/Xray-examples
// https://xtls.github.io/config/
// 常用的 config 文件，不论服务器端还是客户端，都有 5 个部分。外加小小白解读：
// ┌─ 1*log 日志设置 - 日志写什么，写哪里（出错时有据可查）
// ├─ 2_dns DNS-设置 - DNS 怎么查（防 DNS 污染、防偷窥、避免国内外站匹配到国外服务>
// ├─ 3_routing 分流设置 - 流量怎么分类处理（是否过滤广告、是否国内外分流）
// ├─ 4_inbounds 入站设置 - 什么流量可以流入 Xray
// └─ 5_outbounds 出站设置 - 流出 Xray 的流量往哪里去
{
  // 1\_日志设置
  "log": {
    "loglevel": "warning", // 内容从少到多: "none", "error", "warning", "info", "d>
"access": "/home/e1itevps/xray_log/access.log", // 访问记录
    "error": "/home/e1itevps/xray_log/error.log" // 错误记录
  },
  // 2_DNS 设置
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query", // 首选 1.1.1.1 的 DoH 查询，牺牲速度但可>
      "localhost"
    ]
  },
  // 3*分流设置
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      // 3.1 防止服务器本地流转问题：如内网被攻击或滥用、错误的本地回环等
      {
        "type": "field",
        "ip": [
          "geoip:private" // 分流条件：geoip 文件内，名为"private"的规则（本地）
        ],
        "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
      },
      // 3.2 屏蔽广告
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all" // 分流条件：geosite 文件内，名为"category-ads-all"的规则（各种广告域名）
        ],
        "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
      }
    ]
  },
  // 4*入站设置
  // 4.1 这里只写了一个最简单的 vless+xtls 的入站，因为这是 Xray 最强大的模式。如有其他需要，请根据模版自行添加。
  "inbounds": [
    {
      "port": 208,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "我的id", // 填写你的 UUID
            "flow": "xtls-rprx-vision",
          }
],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 2037 // 默认回落到防探测的代理
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false, // 正常使用应确保关闭
          "minVersion": "1.2", // TLS 最低版本设置
          "alpn": ["http/1.1"],
          "certificates": [
            {
              "certificateFile": "/home/e1itevps/xray_cert/xray.crt",
              "keyFile": "/home/e1itevps/xray_cert/xray.key"
            }
          ]
        }
      },
 "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
    }
  ],
  // 5*出站设置
  "outbounds": [
    // 5.1 第一个出站是默认规则，freedom 就是对外直连（vps 已经是外网，所以直连）
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    // 5.2 屏蔽规则，blackhole 协议就是把流量导入到黑洞里（屏蔽）
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}
![11](https://user-images.githubusercontent.com/119770322/205471490-3aeb9b31-8eee-4167-967b-9a9b2da181a3.png)

**Comment by chika0801** [comment]
直接试试这个。https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

**Comment by e1lite** [comment]
> 直接试试这个。https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

你好，我试了一下还是不行，请问是我的Nginx配置的不对造成的吗？我是安装小白文里面进行Nginx配置的。

**Comment by e1lite** [comment]
> 直接试试这个。https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

我之前为了能装上新的nginx将文件的权限修改了，但还是装不上，现在我把文件的权限修改回来了,但安装就会出现这个问题![8F)AKLC(2~@1ZJ(XA4){PL4.png](https://user-images.githubusercontent.com/119770322/205486045-03518dab-8c1d-4452-8707-06c8e9d0c80a.png)

**Comment by e1lite** [comment]
> 直接试试这个。https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

啊啊啊啊，大佬我终于知道哪有问题了，我还是权限这块不熟悉，在这里犯了很多错误，不过现在终于解决了，您写的指导书都把解决方案写清楚了，是我太蠢了都找不出自己错在哪，现在终于解决问题啦！非常感谢
您的指导以及为开发做出的努力！真的非常感谢！！！
