### ISSUE TITLE
想请问一下是不是XTLS+vision版本还不稳定，手机连v2rayNG的时候上国内网很卡

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-examples#94]
像微信直接断网了，剩下的应用也很卡，想问一下只是我的原因吗？还是普遍存在的问题，有什么方法可以改进

PS:电脑端好像不会这样

**Comment by chika0801** [comment]
> 电脑端好像不会这样

说明不是 普遍存在的问题

NG上用，建议你用分应用代理，只选要代理的如浏览器，

我推荐是勾上 启用本地DNS 

域名策略 ipifnonmatch 

预定义规则  绕过大陆和局域网

**Comment by e1lite** [comment]
我按您的方法试了一下，真的很有用，问题解决了，谢谢您！！！🙏🙏今天真的麻烦您了，回答了我的三个问题，都非常的及时而且特别有效，真的无比感谢！很佩服你们，真的了不起，把自由的声音带给了我们！

**Comment by chika0801** [comment]
> 我按您的方法试了一下，真的很有用，问题解决了，谢谢您！！！🙏🙏今天真的麻烦您了，回答了我的三个问题，都非常的及时而且特别有效，真的无比感谢！很佩服你们，真的了不起，把自由的声音带给了我们！

不用谢，不知道回答了你几个。。。

**Comment by e1lite** [comment]
> > 我按您的方法试了一下，真的很有用，问题解决了，谢谢您！！！🙏🙏今天真的麻烦您了，回答了我的三个问题，都非常的及时而且特别有效，真的无比感谢！很佩服你们，真的了不起，把自由的声音带给了我们！
> 
> 
> 
> 不用谢，不知道回答了你几个。。。

- 92-94都是我问的🤣，我太小白了😭
