### ISSUE TITLE
我的电脑端github突然上不去了，请问是什么原因

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-examples#95]
我电脑端的github之前还能上，但我在我的服务器端加入了warp后，电脑端的github突然上不去了，再我将服务器端的warp去掉后，github还是上不去，但这个问题只有windows电脑端出现，v2rayN显示如下![9KDB324)H5Z0WT`RLR%PV57.png](https://user-images.githubusercontent.com/119770322/205717699-36d9f8b5-f238-4a32-ad7e-9edc19e4d892.png)
但我推测应该是v2rayN的问题，因为我的手机端（安卓）和平板（iOS）都能上github。
请问这个问题该如何解决啊？

**Comment by yeyuchen198** [comment]
路由配置里添加一条规则，把github.com设置为proxy，而不是direct

**Comment by PanHsin** [comment]
自己动了默认的路由 或加了自己的规则，并且没写好，否则 默认的规则不会有这样的效果

**Comment by xqzr** [comment]
更新域名、IP库
