### ISSUE TITLE
VLESS-TCP-XTLS fallback to Shadowsocks-2022 udp ovet tcp

### ISSUE THREAD

**Issue by GektorUA** [XTLS/Xray-examples#99]
I am trying to fall back from VLESS-TCP-XTLS to Shadowsocks-2022

server.json (inbounds part):

  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id" : "my-id",
            "flow": "xtls-rprx-direct",
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
           {
             "dest": 1080,
             "xver": 1
           }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "sockopt": {
          "tcpFastOpen": true
        },
        "xtlsSettings": {
        "serverName": "my.site.com",
        "alpn": ["http/1.1"],
        "certificates": [
          {
            "certificateFile" : "/path/to/cer",
            "keyFile" : "/path/to/key"
          }
        ]
        }
      }
    },
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "base64password",
        "level": 1,
        "network": "tcp",
        "tcpSettings": {
           "acceptProxyProtocol": true
        }
      }
    }
  ],
  "outbounds": [
    {
       "protocol": "freedom",
       "settings":
          {
            "domainStrategy": "useipv4"
          }
    }
  ]
}

client.json (only outbound part):

   {
      "tag": "all",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "my.site.com",
            "port": 443,
            "users": [
              {
                "id": "my-id",
                "flow": "xtls-rprx-splice",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "serverName" : "my.site.com",
          "allowInsecure": false,
          "fingerprint": "chrome",
          "cipherSuites": "TLS_AES_128_GCM_SHA256"
        },
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    },
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "my.site.com",
            "port": 443,
            "method": "2022-blake3-aes-128-gcm",
            "password": "base64password",
            "uot": true
          }
        ]
      }
    }

It's works when i am trying connect to shadowsocks with dedicated port (with changed config and port any other, but not 443), but it doesn't work in fallback mode.
Maybe i am doing something wrong? Can someone help me, please?

**Comment by SakuraSakuraSakuraChan** [comment]
Not supported

**Comment by GektorUA** [comment]
There is no way to fallback shadowsocks?

**Comment by Fangliding** [comment]
与example无关
